### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by shadowfox87** [jhertz/elo_calculator#1]
Hi,

Your program is great. It's just what I was looking for. I managed to run it but it only shows me the Elo rating for 1 player, not all. Can you update it so that it calculates the Elo rating for all players? We should also be able to put initial Elo ratings for each player in the tournament. This input can be asked from command prompt.

**Comment by jhertz** [comment]
hey, i'm no longer working on this project, i'm working on a much more sophisticated ratings system 

https://github.com/ripgarpr/garpr

feel free to fork and run with this as needed :)

**Comment by shadowfox87** [comment]
Hey can we chat? I'm on Discord. I want to know if your new program can
pull data from challenge and whether you are still using Elo or something
else.

**Comment by jhertz** [comment]
i'm not on discord. notgarpr is a fully featured website that allows
importing from smashgg, challonge, or tio, supports a variety of ranking
options, and uses TrueSkill (better than elo) as its ranking algorithm. Its
still heavily under development, but you can see our early alpha at
notgarpr.com

feel free to read through the source to understand stuff, its all python :)

**Comment by shadowfox87** [comment]
What's your slack link? Also, I read the documentation. I think you should take into account the set score such that there is a difference between 2-0 and 2-1. I need it for Ygopro, an online Yugioh simulator (http://discord.me/ygopro). You can chat on discord without downloading anything or registering an account.

**Comment by jhertz** [comment]
Sorry, were not particularly interested in adding set score features. Our slack is for devs if youd like to join the project as a dev, but were very much focused on smash rn.

**Comment by shadowfox87** [comment]
It's ok, I think I will use the SkillKeeper program that was in the SSBM forums.
